/**
 * Created by milad on 1/28/18.
 */
export const FETCHING = "FETCHING";
export const CANCEL_FETCHING = "CANCEL_FETCHING";

export const UPDATE_LOGIN_TOKEN = "UPDATE_LOGIN_TOKEN";
export const DELETE_LOGIN_TOKEN = "DELETE_LOGIN_TOKEN";

export const SET_STUDENT_INFO = "SET_STUDENT_INFO";
export const REMOVE_STUDENT_INFO = "REMOVE_STUDENT_INFO";

export const SET_HEADER_SUBTITLE = "SET_HEADER_SUBTITLE";

export const UI_SET_SNACK_BAR = "UI_SET_SNACK_BAR";
export const UI_HIDE_SNACK_BAR = "UI_HIDE_SNACK_BAR";

export const UI_SHOW_WARNING_DIALOG = "UI_SHOW_WARNING_DIALOG";
export const UI_HIDE_WARNING_DIALOG = "UI_HIDE_WARNING_DIALOG";