/**
 * Created by milad on 1/28/18.
 */
export const FETCHING = "FETCHING";
export const CANCEL_FETCHING = "CANCEL_FETCHING";

export const UPDATE_LOGIN_TOKEN = "UPDATE_LOGIN_TOKEN";
export const DELETE_LOGIN_TOKEN = "DELETE_LOGIN_TOKEN";

export const SET_STUDENT_INFO = "SET_STUDENT_INFO";
export const REMOVE_STUDENT_INFO = "REMOVE_STUDENT_INFO";